### ISSUE TITLE
Develop environment.yml and requirements.txt for baseline earthquake notebook

### ISSUE THREAD

**Issue by Toble007** [Data-ScienceHub/mlcommons-science#12]
We need to solve the environment from prior experiments that way we build a basis for future analysis and comparison.  This is tied to #14 , but focuses in on library versions and compatibilities than optimizing the algorithms and code.

Library dependencies that are in the current platform include:

- cloudmesh-common
- matplotlib
- numpy
- pandas
- psutil
- scipy
- tensorflow
- tensorflow_datasets
- tqdm

**Comment by rknuu** [comment]
Reviewing the base version over in google colab, the following versions are part of the configuration:

- Python=3.7.12
- matplotlib=3.2.2
- numpy=1.19.5
- pandas=1.3.5
- psutil=5.4.8
- scipy=1.4.1
- tensorflow=2.7.0
- tensorflow-datasets=4.0.1
- tqdm=4.62.3
- cloudmesh-common=4.3.80

These versions don't directly solve in conda, so there's likely a specific ordering or patch versions we'll need to target.

**Comment by laszewsk** [comment]
google colab requirement add to

https://github.com/Data-ScienceHub/mlcommons-science/blob/main/code/requirements-colab.txt

removed the cloudmesh common version as we want the newest here
