### ISSUE TITLE
Week 1 Activities

### ISSUE THREAD

**Issue by rknuu** [Data-ScienceHub/mlcommons-science#2]
There's a lot of technologies that were mentioned in our first meeting that we need to get comfortable with.  For this task, lets get familiar with the following:

 lmod - lua module and environment management (used on rivanna)
- pip / conda env - python package management
- SLURM - an HPC batch job runner
- papermill - parameterized jupyter notebooks
- horovod - distributed framework for running multiple deep learning frameworks
- MLCube - MLCommons repeatable machine learning framework with multiple backends.
- singularity - container runtimes targeting HPC clusters
- docker

- [x] @rknuu 
- [x] @Toble007 
- [x] jakekolessar

**Comment by Toble007** [comment]
I read through and reviewed the Get started on these technologies. I understand these and when I could use these but am still a beginner.

On another note, thanks for putting this list together. I didn't get most of this stuff on my list.
