### ISSUE TITLE
Missing topearthquakes_20.csv and pix_faults_SmallJan21.csv from earthquake dataset

### ISSUE THREAD

**Issue by rknuu** [Data-ScienceHub/mlcommons-science#20]
The public dataset in google drive for the earthquake benchmark is missing the following files:

* topearthquakes_20.csv
* pix_faults_SmallJan21.csv

This prevents the running of the benchmark notebook. near the beginning.  We need to update the google drive to include the dataset, or upload to rivanna directly until there's a more permanent home for the data.\

- [x] locate data set: its on dgx
- [x]  copy dataset to rivanna

**Comment by laszewsk** [comment]
on dgx 

ls -1 /raid/colabdata/EarthquakeDec2020/
1950start
Outputs
pix_faults_SmallJan21.csv
topearthquakes_20.csv
ValidationEARTHQDGX-Transformer1
ValidationEARTHQN-Transformer3

**Comment by rknuu** [comment]
Data is now loaded both in rivanna (in `/project/ds6011-sp22-002/eq/data` and in laszewsk/mlcommons-data-earthquake
