### ISSUE TITLE
discuss submodules

### ISSUE THREAD

**Issue by laszewsk** [Data-ScienceHub/mlcommons-science#32]
this will need an explicit guide

- [x] we will just ad a readme
- [x] provide install instructions
- [x] implement submodules

**Comment by laszewsk** [comment]
we discussed in meeting that due to difficulties and a lack of community documentation we had to restart the repo from scratch. This required owership of github. This allowed us more easyly to interface with the repo already established by mlcommons

**Comment by rknuu** [comment]
Discussed with group, conclusion by the students @Toble007 @jakekolessar and myself that the way this is organized functions for our purposes, and we have full access to the submodule over to the customer's mlcommons-science.

We agreed that this leverages git for how it was designed and that contributions can be obtained by inspecting the insights tab in the other project.

We are aware that we can create our own fork of that repository to mirror the code.

**Comment by Toble007** [comment]
I agree with what @rknuu said. The way this is currently implemented is fine.
