### ISSUE TITLE
License agreement:

### ISSUE THREAD

**Issue by laszewsk** [Data-ScienceHub/mlcommons-science#39]
Please send a comment to this issue while repeating the following sentence. This way we have a document in github. 

"I FIRSTNAME LASTNAME, agree that any participation in this project will be conducted using Apache 2.0 license."

**Comment by rknuu** [comment]
I Robert Knuuti, agree that any participation in this project will be conducted using Apache 2.0 license.

**Comment by jakekolessar** [comment]
I Jake Kolessar, agree that any participation in this project will be conducted using Apache 2.0 license.
