### ISSUE TITLE
Reconfigure EQ Notebook to run on Rivanna

### ISSUE THREAD

**Issue by rknuu** [Data-ScienceHub/mlcommons-science#46]
The current state of the notebook works only when run on Google Colab.  We'd like to make this work on rivanna and local workstations with the minimal amount of code changes.

**Comment by laszewsk** [comment]
see my comments to requirements.txt whcih must be unversioned.
we have special requirements for each of the machines and need to identify whch work
* requirements-robert.txt (runs on roberts machine)
* requirements-rivanna.txt
* requirements-collab.txt (doe not include jupyer and jupyterlab)
* requirements.txt (no versioning here)

In general we like to use the most up to date version we try not to replicate google collab, but the newets version in general. we can try however two versions a) one with google colab settings, the other once with the newets. 
I had difficulties on my machine with the colab setting as it did not work and only after i made everything versionless thinsg worked
