### ISSUE TITLE
code: images are to faint

### ISSUE THREAD

**Issue by laszewsk** [Data-ScienceHub/mlcommons-science#52]
locate "# Gregor: images are too faint"

identify why the images are too faint. they should show some data more prominently. I have seen this before in other versions.

Maybe just the scale needs to be adjusted?

- [x] create *-buttler.ipynb or thomas if you prefer
- [x] verify that it works for you on rivanna 
- [x] make sure that the changes are only applied to the plot and not the internal data (maybe you have to copy df , and so on ...
- [x] needs to be independently verified by somone else
- [x] after verification work with gregor to integrate in *-gregor.ipynb

**Comment by Toble007** [comment]
I have two options, either make the groups of graphs work off of the local minimum and maximums for the sets of graphs or change the color scheme. A changing color scheme will likely not be able to fix it. I have implemented local minimum and maximums for my local code, will update code when latest version is uploaded and verify it works.

**Comment by Toble007** [comment]
https://github.com/laszewsk/mlcommons/blob/main/benchmarks/earthquake/mar2022/FFFFWNPFEARTHQ_newTFTv29-gregor.ipynb

pushed changes.

Please let me know if this is a good fix or another way needs to be implemented that keeps maximum and minimum values either across all values or just the ones graphed.

**Comment by laszewsk** [comment]
did not work, CalculatedTimeSeries is not defined
please redo in separate file *-buttler.ipynb so we can test that before merge

**Comment by Toble007** [comment]
I have added a _thomas.ipynb, only difference between that and the gregor code currently is cell 22 the cell after the plotimages function cell, the cell which makes the faint graphs.

**Comment by rknuu** [comment]
I've reviewed and integrated Thomas's code.  See laszewsk/mlcommons#15 for the PR ready for merge.  I think there were some merge issues with the prior testing that may have caused this issue.
